Repository TokTok/bTox, pull requests merged in 2022-02, with the labels that each got.

#17 feat: add drawer menu and skeleton settings/profile pages
  lib/contact_list_page.dart
  lib/profile.dart
  lib/settings.dart
  lib/strings.dart
Labels: enhancement

#19 feat: Add state and the ability to set the nick and status message
  lib/app_state.dart
  lib/contact_list_page.dart
  lib/profile.dart
  lib/settings.dart
  lib/strings.dart
Labels: enhancement

#24 feat: Start keeping messages in the database
  lib/chat_page.dart
  lib/contact_list_page.dart
  lib/db/database.dart
Labels: enhancement

#26 fix: Fix add-contact page being unusable with smaller viewports
  lib/add_contact_page.dart
Labels: bug

#27 chore: Measure code coverage
  .github/workflows/ci.yml
Labels: chore
