Repository TokTok/bTox, pull requests merged in 2025-02, with the labels that each got.

#55 docs: Translations update from Hosted Weblate
  lib/l10n/app_bg.arb
Labels: documentation

#57 chore: Add netlify push/preview workflow.
  .github/workflows/release.yml
  .netlify/Dockerfile
  .netlify/state.json
  tools/prepare
Labels: chore

#56 docs: Translations update from Hosted Weblate
  lib/l10n/app_bg.arb
Labels: documentation

#59 feat: Add experimental web FFI.
  .github/workflows/ci.yml
  .netlify/Dockerfile
  cspell.config.yaml
  lib/api/toxcore/tox.dart
  lib/btox_app.dart
  lib/db/shared.dart
  lib/db/unsupported.dart
  lib/ffi/tox_constants.dart
  lib/ffi/tox_constants.native.dart
  lib/ffi/tox_constants.web.dart
  lib/ffi/tox_ffi.dart
  lib/ffi/tox_ffi.native.dart
  lib/ffi/tox_ffi.web.dart
  lib/ffi/tox_library.dart
  lib/ffi/tox_library.ffi.dart
  lib/ffi/tox_library.js.dart
  lib/ffi/tox_library.unsupported.dart
  lib/ffi/toxcore.dart
  lib/ffi/toxcore.native.dart
  lib/models/crypto.dart
  lib/models/messaging.dart
  lib/packets/messagepack.dart
  lib/packets/messagepack/packer.dart
  lib/packets/messagepack/unpacker.dart
  lib/pages/create_profile_page.dart
  lib/pages/select_profile_page.dart
  lib/providers/sodium.dart
  lib/providers/tox.dart
  pubspec.lock
  pubspec.yaml
  test/btox_app_test.dart
  test/mocks/fake_tox_constants.dart
  test/mocks/fake_toxcore.dart
  test/persistence_test.dart
  tools/prepare
  tools/prepare-web
  web/.gitignore
  web/index.html
Labels: enhancement

#66 docs: Translations update from Hosted Weblate
  lib/l10n/app_ta.arb
Labels: documentation

#65 chore: Update linux build to the latest flutter defaults.
  .metadata
  .restyled.yaml
  android/app/src/main/kotlin/chat/tox/btox/MainActivity.kt
  linux/CMakeLists.txt
  linux/flutter/CMakeLists.txt
  linux/runner/CMakeLists.txt
  linux/runner/main.cc
  linux/runner/my_application.cc
  linux/runner/my_application.h
  windows/CMakeLists.txt
  windows/flutter/CMakeLists.txt
  windows/runner/CMakeLists.txt
  windows/runner/Runner.rc
  windows/runner/flutter_window.cpp
  windows/runner/main.cpp
  windows/runner/runner.exe.manifest
  windows/runner/utils.cpp
  windows/runner/win32_window.cpp
  windows/runner/win32_window.h
Labels: chore

#71 chore: Update to latest Android generated files.
  .github/workflows/ci.yml
  .github/workflows/pages.yml
  .metadata
  android/.gitignore
  android/app/build.gradle.kts
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/chat/tox/btox/MainActivity.kt
  android/app/src/main/res/values-night/styles.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/profile/AndroidManifest.xml
  android/build.gradle
  android/build.gradle.kts
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
  android/settings.gradle.kts
Labels: chore

#70 chore: Rename release to draft workflow; add reviewable config.
  .github/workflows/draft.yml
  .github/workflows/release.yml
  .reviewable/completion.js
  .reviewable/settings.yaml
Labels: chore

#60 feat: Parse the tox core events and display them in the log.
  lib/api/toxcore/tox.dart
  lib/api/toxcore/tox_events.dart
  lib/db/native.dart
  lib/ffi/toxcore.dart
  lib/models/crypto.dart
  lib/providers/tox.dart
  lib/widgets/main_menu.dart
  test/mocks/fake_toxcore.dart
Labels: enhancement

#61 feat: Properly save/load tox keys.
  lib/api/toxcore/tox.dart
  lib/api/toxcore/tox_options.dart
  lib/ffi/tox_library.js.dart
  lib/ffi/toxcore.dart
  lib/logger.dart
  lib/models/bootstrap_nodes.dart
  lib/models/crypto.dart
  lib/pages/contact_list_page.dart
  lib/providers/tox.dart
  lib/widgets/connection_status_icon.dart
  lib/widgets/contact_list_item.dart
  lib/widgets/main_menu.dart
  macos/Runner/Configs/AppInfo.xcconfig
  pubspec.yaml
  test/btox_app.png
  test/btox_app_test.dart
  test/mocks/fake_toxcore.dart
  test/persistence_test.dart
  web/manifest.json
Labels: enhancement

#62 feat: Add an icon for bTox.
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  assets/images/btox-icon.png
  assets/images/btox.svg
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png
  pubspec.lock
  pubspec.yaml
  web/favicon.png
  web/icons/Icon-192.png
  web/icons/Icon-512.png
  web/icons/Icon-maskable-192.png
  web/icons/Icon-maskable-512.png
  windows/runner/resources/app_icon.ico
Labels: enhancement

#73 chore: Add configuration for imgbot.
  .imgbotconfig
Labels: chore

#68 test: Add a test walking through most of the UIs.
  .github/workflows/ci.yml
  assets/fonts/DejaVuSans.ttf
  lib/models/bytes.dart
  lib/models/crypto.dart
  lib/pages/chat_page.dart
  lib/pages/contact_list_page.dart
  lib/pages/create_profile_page.dart
  lib/providers/tox.dart
  lib/widgets/connection_status_icon.dart
  lib/widgets/friend_request_message_field.dart
  lib/widgets/main_menu.dart
  lib/widgets/nickname_field.dart
  lib/widgets/status_message_field.dart
  pubspec.yaml
  test/btox_app.png
  test/btox_app_test.dart
  test/goldens/add_contact.png
  test/goldens/add_contact_empty_message.png
  test/goldens/add_contact_filled.png
  test/goldens/add_contact_incomplete.png
  test/goldens/add_contact_too_long_message.png
  test/goldens/chat_empty.png
  test/goldens/chat_hello.png
  test/goldens/contact_list_empty.png
  test/goldens/contact_list_one.png
  test/goldens/drawer.png
  test/goldens/drawer_alice.png
  test/goldens/entry.png
  test/goldens/profile.png
  test/goldens/profile_alice.png
  test/goldens/profile_applied.png
  test/goldens/settings.png
  test/goldens/settings_delete.png
  test/mocks/fake_bootstrap_nodes.dart
  test/mocks/fake_sodium.dart
  test/mocks/fake_toxcore.dart
  test/widget_test.dart
Labels: test

#75 chore: Add nightly release pushes and netlify preview build.
  .clog.toml
  .github/workflows/ci.yml
  .github/workflows/draft.yml
  CHANGELOG.md
Labels: chore

#76 chore: Fix windows and linux packaging.
  .github/workflows/ci.yml
  .github/workflows/pages.yml
  linux/CMakeLists.txt
Labels: chore

#77 docs: Add screenshot to readme.
  README.md
Labels: documentation

#69 chore: Update to the latest ios/macos generated code.
  .metadata
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  macos/Podfile
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  macos/Runner/Configs/AppInfo.xcconfig
  macos/Runner/DebugProfile.entitlements
  macos/Runner/Release.entitlements
  macos/RunnerTests/RunnerTests.swift
  pubspec.lock
Labels: chore

#78 perf: Speed up rendering of identicons.
  lib/models/identicon.dart
  lib/widgets/circle_identicon.dart
  test/btox_app_test.dart
  test/goldens/drawer.png
  test/goldens/drawer_alice.png
  test/identicon_test.dart
  test/mocks/image_data.dart
  test/widget_test.dart
Labels: performance

#80 feat: Add chat bubbles and prettier text entry box.
  l10n.yaml
  lib/api/toxcore/tox_events.dart
  lib/btox_app.dart
  lib/l10n/app_en.arb
  lib/models/crypto.dart
  lib/models/identicon.dart
  lib/models/messaging.dart
  lib/models/persistence.dart
  lib/packets/message_packet.dart
  lib/packets/messagepack/packer.dart
  lib/packets/messagepack/tags.dart
  lib/packets/messagepack/unpacker.dart
  lib/packets/packet.dart
  lib/pages/add_contact_page.dart
  lib/pages/chat_page.dart
  lib/pages/contact_list_page.dart
  lib/pages/create_profile_page.dart
  lib/pages/settings_page.dart
  lib/pages/user_profile_page.dart
  lib/providers/tox.dart
  lib/widgets/attachment_button.dart
  lib/widgets/attachment_selector.dart
  lib/widgets/bubble.dart
  lib/widgets/chat_bubble.dart
  lib/widgets/circle_identicon.dart
  lib/widgets/contact_list_item.dart
  lib/widgets/friend_request_message_field.dart
  lib/widgets/main_menu.dart
  lib/widgets/message_input.dart
  lib/widgets/nickname_field.dart
  lib/widgets/status_message_field.dart
  lib/widgets/tox_id_field.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  macos/Runner/DebugProfile.entitlements
  macos/Runner/Release.entitlements
  pubspec.lock
  pubspec.yaml
  test/btox_app_test.dart
  test/chat_page_test.dart
  test/goldens/chat_empty.png
  test/goldens/chat_hello.png
  test/goldens/chat_page/empty.png
  test/goldens/chat_page/messages.png
  test/goldens/chat_page/messages_long.png
  test/goldens/chat_page/messages_time.png
  test/goldens/drawer.png
  test/goldens/drawer_alice.png
  test/persistence_test.dart
  test/widget_test.dart
Labels: enhancement

#85 docs: Translations update from Hosted Weblate
  lib/l10n/app_bg.arb
Labels: documentation

#86 fix: Support platform queries on web.
  lib/ffi/tox_library.ffi.dart
  lib/platform/any_platform.dart
  lib/platform/io_platform.dart
  lib/platform/js_interop_platform.dart
  lib/platform/platform_api.dart
  lib/platform/unsupported_platform.dart
  lib/providers/keyboard_height.dart
  lib/service.dart
  lib/widgets/attachment_selector.dart
Labels: bug

#83 feat: Add emoji picker.
  lib/background_service.dart
  lib/main.dart
  lib/pages/chat_page.dart
  lib/pages/settings_page.dart
  lib/widgets/chat_item.dart
  lib/widgets/chat_text.dart
  lib/widgets/chat_text_bubble.dart
  lib/widgets/chat_text_emoji.dart
  lib/widgets/message_input.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  test/chat_page_test.dart
  test/goldens/chat_empty.png
  test/goldens/chat_hello.png
  test/goldens/chat_page/emoji_picker.png
  test/goldens/chat_page/emoji_picker_closed.png
  test/goldens/chat_page/emoji_picker_tapped.png
  test/goldens/chat_page/emoji_sent.png
  test/goldens/chat_page/empty.png
  test/goldens/chat_page/messages.png
  test/goldens/chat_page/messages_long.png
  test/goldens/chat_page/messages_time.png
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement
