Repository TokTok/bTox, pull requests merged in 2025-03, with the labels that each got.

#84 feat: Add message context menu.
  lib/models/attachment.dart
  lib/pages/chat_page.dart
  lib/widgets/attachment_selector.dart
  lib/widgets/chat_context_menu.dart
  lib/widgets/chat_item.dart
  lib/widgets/chat_text.dart
  lib/widgets/message_input.dart
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  test/chat_page_test.dart
  test/goldens/chat_page/emoji_picker.png
  test/goldens/chat_page/emoji_picker_tapped.png
  test/goldens/chat_page/message_context_menu.png
Labels: enhancement

#87 feat: Better support for different types of chat content.
  .restyled.yaml
  dart_test.yaml
  lib/db/database.dart
  lib/models/attachment.dart
  lib/models/bytes.dart
  lib/models/content.dart
  lib/models/crypto.dart
  lib/models/messaging.dart
  lib/models/persistence.dart
  lib/packets/converters.dart
  lib/packets/message_packet.dart
  lib/pages/chat_page.dart
  lib/pages/contact_list_page.dart
  lib/widgets/attachment_selector.dart
  lib/widgets/chat_content.dart
  lib/widgets/chat_item.dart
  lib/widgets/chat_text.dart
  lib/widgets/message_input.dart
  pubspec.lock
  pubspec.yaml
  test/chat_page_test.dart
  test/models/content_test.dart
  test/models/persistence_test.dart
Labels: enhancement

#88 feat: Add map location bubble.
  .imgbotconfig
  .imgbotconfig.json
  lib/providers/map_tile.dart
  lib/widgets/chat_content.dart
  lib/widgets/chat_item.dart
  lib/widgets/chat_location_bubble.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/fake_tile_provider.dart
  test/widgets/chat_content_test.dart
Labels: enhancement

#89 refactor: Better support unknown content data.
  lib/api/toxcore/tox_events.dart
  lib/models/content.dart
  lib/packets/converters.dart
  lib/packets/messagepack/message_data.dart
  lib/packets/messagepack/message_data_json_converter.dart
  lib/packets/messagepack/packer.dart
  lib/packets/messagepack/unpacker.dart
  test/models/content_test.dart
  test/packets/messagepack/message_data_test.dart
Labels: refactor

#90 docs: Translations update from Hosted Weblate
  lib/l10n/app_lv.arb
Labels: documentation
